### PR TITLE
Portfolio-6

### PR DESCRIPTION
**Pull request by Deepakgupta04**

### CODE REVIEW

**Comment by Deepakgupta04** [comment]
Personal portfolio

**Review by E-fais — CHANGES_REQUESTED** [review]
Hey , please dont change README file. 
Create a new folder with title of your project and add your new files in that folder,

**Comment by sonalikari** [comment]
@Deepakgupta04 Kindly read README.md carefully.

**Comment by Deepakgupta04** [comment]
Added on a separate folder,
"Personal Portfolio"

**Pull request closed without merging**
